import { Inter } from "next/font/google";
import "./globals.css";
import HomeHeading from "./components/HomeHeading";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" />
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" ></script>
            </head>
            <body className={inter.className}>
                <HomeHeading />
                <div className="pt-5 text-center">
                    <Link href={"/"} className="btn btn-dark text-white mr-2">Back to Home</Link>
                    <Link href={"/add"} className="btn btn-dark text-white">Add User Button</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
